### ISSUE TITLE
Some parent interface API signatures are dropped on Kotlin 1.7.20

### ISSUE THREAD

**Issue by drewhamilton** [Kotlin/binary-compatibility-validator#100]
I'm upgrading a project from 1.7.10 to 1.7.20, and `apiDump` is removing some function signatures that still exist in my class's parent interface. Worth noting that:
1. The parent interface is part of `kotlin-compiler-embeddable`, so directly tied to the Kotlin version.
2. Of the 4 missing signatures, 3 are extension functions and the other 1 is deprecated.

My (unchanged) class is [here](https://github.com/drewhamilton/Poko/blob/drew/kotlin-1.7.20/poko-compiler-plugin/src/main/kotlin/dev/drewhamilton/poko/PokoCommandLineProcessor.kt), the parent interface is [here](https://github.com/JetBrains/kotlin/blob/v1.7.20/compiler/plugin-api/src/org/jetbrains/kotlin/compiler/plugin/CommandLineProcessor.kt), and the build failure is pasted below.

```
> API check failed for project poko-compiler-plugin.
  --- /home/runner/work/Poko/Poko/poko-compiler-plugin/api/poko-compiler-plugin.api
  +++ /home/runner/work/Poko/Poko/poko-compiler-plugin/build/api/poko-compiler-plugin.api
  @@ -1,12 +1,8 @@
   public final class dev/drewhamilton/poko/PokoCommandLineProcessor : org/jetbrains/kotlin/compiler/plugin/CommandLineProcessor {
   	public fun <init> ()V
  -	public fun appendList (Lorg/jetbrains/kotlin/config/CompilerConfiguration;Lorg/jetbrains/kotlin/config/CompilerConfigurationKey;Ljava/lang/Object;)V
  -	public fun appendList (Lorg/jetbrains/kotlin/config/CompilerConfiguration;Lorg/jetbrains/kotlin/config/CompilerConfigurationKey;Ljava/util/List;)V
  -	public fun applyOptionsFrom (Lorg/jetbrains/kotlin/config/CompilerConfiguration;Ljava/util/Map;Ljava/util/Collection;)V
   	public fun getPluginId ()Ljava/lang/String;
   	public fun getPluginOptions ()Ljava/util/Collection;
   	public fun processOption (Lorg/jetbrains/kotlin/compiler/plugin/AbstractCliOption;Ljava/lang/String;Lorg/jetbrains/kotlin/config/CompilerConfiguration;)V
  -	public fun processOption (Lorg/jetbrains/kotlin/compiler/plugin/CliOption;Ljava/lang/String;Lorg/jetbrains/kotlin/config/CompilerConfiguration;)V
   }
   
   public final class dev/drewhamilton/poko/PokoComponentRegistrar : org/jetbrains/kotlin/compiler/plugin/ComponentRegistrar {
```

**Comment by qwwdfsad** [comment]
We are investigating

**Comment by qwwdfsad** [comment]
This change is safe -- in 1.7.20 the compilation strategy of kotlin-compiler-embeddable [has been changed](https://github.com/JetBrains/kotlin/commit/a7bae6f4c4bf520cec9f5309a8842210703f21a5), so now default interface methods are compiled as `default` on JVM.
