### ISSUE TITLE
0.12.0 produces empty API files when applied to root project

### ISSUE THREAD

**Issue by colinrtwhite** [Kotlin/binary-compatibility-validator#103]
Hi, after updating `0.11.1` -> `0.12.0` the `apiDump` task produces empty API files in my project. The project applies the plugin to the root project. [Here's the PR](https://github.com/coil-kt/coil/pull/1515) to update the plugin.

**Comment by qwwdfsad** [comment]
Thanks for the repro!

Fixed in 0.12.1, should be available on Maven Central soon
