### ISSUE TITLE
New functions in a .kt file are marked as breaking

### ISSUE THREAD

**Issue by mattinger** [Kotlin/binary-compatibility-validator#106]
If i have an existing KT file with a function:

```
@Composable
fun CLButton(.....) { }
```

And i add new function to it:

```
@Composable
fun foo() { }
```

The apiCheck task will fail.  Adding new functions isn't really a breaking change unless they are added to an interface, or added as abstract functions (or even potentially open functions as well).

**Comment by mattinger** [comment]
I suspect this is true because the algorithm is merely doing a file diff?

**Comment by qwwdfsad** [comment]
Please see https://github.com/Kotlin/binary-compatibility-validator/issues/107#issuecomment-1293901120

**Comment by ilya-g** [comment]
Also, see #70 for a more detailed explanation *why* this tool works this way.
