### ISSUE TITLE
How to override the `apiBuild` task in Groovy

### ISSUE THREAD

**Issue by radixdev** [Kotlin/binary-compatibility-validator#109]
<img width="1384" alt="image" src="https://user-images.githubusercontent.com/2373546/201222094-5cfe7bc3-ca26-4696-9bc4-bff98bd99250.png">

title. I get the following error for:
```
apiBuild {
  // "jar" here is the name of the default Jar task producing the resulting jar file
  // in a multiplatform project it can be named "jvmJar"
  // if you applied the shadow plugin, it creates the "shadowJar" task that produces the transformed jar
  inputJar.value(new File("android-sdk-base/build/outputs/sources/android-sdk-base-sources.jar"))
}
```

```
Caused by: org.gradle.internal.metaobject.AbstractDynamicObject$CustomMessageMissingMethodException: Could not find method apiBuild() for arguments [quality_3w8dpqhsp24rs3ntbbp280wfa$_run_closure5@7d0ce1f1] on project ':android-sdk-base' of type org.gradle.api.Project.
```

in 0.12.1 of the library

**Comment by ilya-g** [comment]
Yes, this is an example of configuration in a Kotlin build script.
In a Groovy build script, try using `tasks.named('apiBuild') { ... }` instead of `tasks.apiBuild { ... }`

**Comment by radixdev** [comment]
Is this not due to https://github.com/Kotlin/binary-compatibility-validator/blob/3a9d921dbb8f54efdec08465da6d34c4e04435c5/src/main/kotlin/BinaryCompatibilityValidatorPlugin.kt#L58-L70 and no task with the name "apiBuild" being registered?

**Comment by ilya-g** [comment]
Note that you need the version to be at least 0.12.0 in order to specify jar as the source of apiBuild task.
And in a multiplatform project, it's likely called `jvmApiBuild`.

**Comment by radixdev** [comment]
I was on 0.12.1 (see my original post), I had a typo in my follow-up comment.

**Comment by Chozzle** [comment]
I'm also seeing this issue.
