### ISSUE TITLE
Bug in 'apiBuild' Documentation 

### ISSUE THREAD

**Issue by radixdev** [Kotlin/binary-compatibility-validator#111]
Issue: Attempting to follow https://github.com/Kotlin/binary-compatibility-validator#optional-parameters results in an error when building the project. 

Repro project: https://github.com/radixdev/bcv-apiBuild-bug-repro
https://github.com/radixdev/bcv-apiBuild-bug-repro/blob/main/app/build.gradle#L57-L59

My aims: All I want to do is override the `apiBuild` task and set a custom directory for classes that the "binary" is compiled from. Or set a jar or whatever. My library is obfuscated by r8 and this validator is flagging changes made to the private signatures as well. Another fix would be have a "whitelist" of annotations where only classes annotated with "@Keep" are checked. Right now, this validator only looks at a blacklist of annotations via `nonPublicMarkers` and the inverse isn't an option.

**Comment by ilya-g** [comment]
It's mostly likely that the obfuscator just renames the functions and classes in the resulting jar, but doesn't touch Kotlin metadata which stores information important to Kotlin, like visibilities of declarations. Therefore the metadata becomes inconsistent with the declarations and things that were internal are no longer considered so by Kotlin and binary compatibility validator.
As a workaround, you can try to move all internal things to a separate package and add its name to the list of ignored packages (`ignoredPackages` option). Just ensure that the package itself is not renamed during the obfuscation.

**Comment by radixdev** [comment]
Okay, due to the bug in the `apiBuild` documentation, would you instead be open to a pull request where instead of a blacklist of annotations to skip, a whitelist of annotations to keep is added? That would be more feasible for my usecase vs moving all internal classes to their own packages.

**Comment by radixdev** [comment]
Finally found the proper api to obtain the task and the stated documentation afterwards also did not work. Achieved via other means.
