### ISSUE TITLE
Provide `@ExperimentalAPI` annotation

### ISSUE THREAD

**Issue by Kantis** [Kotlin/binary-compatibility-validator#120]
Providing an `@ExperimentalAPI` annotation which is picked up and added to the API dump could be useful for several reasons:

* Distinguishes when experimental API is broken, which might be more tolerable than other breaking changes
* Promotions from experimental to stable API becomes visible from the API Dump

**Comment by qwwdfsad** [comment]
It doesn't seem to fit the purpose of the BCV.
`Experimental` status and its stability are typically decided on a case-by-case basis for each library, and guarantees provided may vary. I would very much like to avoid introducing any "standard" experimental API marker to avoid its meaning inflation

**Comment by Kantis** [comment]
How about the ability to include an annotation into the dump?

```kotlin
tasks {
  apiBuild {
    includeAnnotations += listOf("my.library.Experimental")
  }
}
```

And then people can use it however they like.. :)
