### ISSUE TITLE
Support output folder configuration

### ISSUE THREAD

**Issue by saadfarooq** [Kotlin/binary-compatibility-validator#127]
Our mono-repo uses a hierarchy of projects where the API definitions are kept in a sub-folder named `api` under each project. When I run `apiDump`, those checked in folders all get overridden because by default the plugin writes the `api` folder. Is there any way to customize the output folder name?

**Comment by LVMVRQUXL** [comment]
There is still no way to configure the output folder in version [0.12.1](https://github.com/Kotlin/binary-compatibility-validator/releases/tag/0.12.1).
This is a useful feature that should be implemented in my opinion.

**Comment by fzhinkin** [comment]
Related issue: https://github.com/Kotlin/binary-compatibility-validator/issues/128
