### ISSUE TITLE
Conflict with modules named `:api`

### ISSUE THREAD

**Issue by gabrieldrn** [Kotlin/binary-compatibility-validator#128]
I have a project with `:core` and `:core:api` as Gradle modules, plus a `:featureX` module implementing `:core:api`. Execution of `apiDump` results with an error:
```
./gradlew apiDump
> Task :featureX:compileReleaseKotlin FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':featureX:compileReleaseKotlin'.
> Could not resolve all files for configuration ':featureX:detachedConfiguration8'.
   > Failed to transform api.jar to match attributes {artifactType=classpath-entry-snapshot, org.gradle.libraryelements=jar, org.gradle.usage=java-runtime}.
      > Execution failed for ClasspathEntrySnapshotTransform: /path/to/my/project/core/api/build/libs/api.jar.
         > Check failed.
```
The error does not give relevant information, but when checking my codebase, I saw that the generation of the .api file of `:core:api` have overwritten the directory, resulting in a complete deletion of the `src` folder of `:core:api`.

I bet this is a conflicting edge case between the "api" file extension and modules named `:api`.

**Comment by aSemy** [comment]
Do you have multiple subprojects that end in `:api`? Might it be this issue https://github.com/gradle/gradle/issues/847 ?

**Comment by gabrieldrn** [comment]
@aSemy 
Only one. And yes, it seems to be related:
> This effectively prevents users from using short names for projects like `api` or `jdk6`.
I don't have modules with the same name, but this sentence points exactly the issue I'm facing.

**Comment by fzhinkin** [comment]
@gabrieldrn, the recent release (https://github.com/Kotlin/binary-compatibility-validator/releases/tag/0.14.0) added a way to configure an output directory for dumps so it is no longer `api` (conflicting with your module). Could you please check if that solves the issue?

**Comment by gabrieldrn** [comment]
@fzhinkin Thanks, I'll have a look asap!

**Comment by gabrieldrn** [comment]
I can't reproduce this with version 0.14.0, everything look good 👍🏻 
Thank you for addressing this issue, closing.
