### ISSUE TITLE
Prevent `apiCheck` task fail until tests are finished.

### ISSUE THREAD

**Issue by e5l** [Kotlin/binary-compatibility-validator#14]
We often run CI integration tests without running `apiDump`. The `apiCheck` task can fail the build without running tests or showing the results.

Please consider delaying running(or failing) `apiCheck` task until tests are finished so we can observe test results.

**Comment by ansman** [comment]
I don't think that this is something that the library should do. You can use the `--continue` flag to keep running tasks after a failure.
