### ISSUE TITLE
Copyright notice in generated file

### ISSUE THREAD

**Issue by LVMVRQUXL** [Kotlin/binary-compatibility-validator#152]
I would like to add a copyright notice to the generated file published on my repository, but this change will fail the checks.
Is it possible to add comments to the generated file?
If not, then it could be an idea of enhancement for the plugin.

I'm using the version [0.12.1](https://github.com/Kotlin/binary-compatibility-validator/releases/tag/0.12.1).

Thank you for considering this issue.

**Comment by qwwdfsad** [comment]
It could be a potential feature for BCV indeed.

Could you please elaborate on the reasoning behind the copyright on the ABI dump? What exactly does it protect or what is the legal reasoning here?

**Comment by LVMVRQUXL** [comment]
Sure @qwwdfsad.

Because our ABI dump can be updated by external contributors (after forking the project, adding a feature and running the `apiDump` task), I would like to add a copyright notice indicating that the file is governed by the project's license.
For instance, this is for the [Kotools Types](https://github.com/kotools/types) library.

Let me know if this is not clear, I try my best to express the intent. 😅

**Comment by fzhinkin** [comment]
It seems fairly simple to add an option that will include some header (and a footer, if needed) to the generated dump. However, some license notes contain dates (like `Copyright 2016-2024 JetBrains s.r.o.`) and it's unclear how it should be updated. Do we need to also support some primitive templating engine then? :\

**Comment by fzhinkin** [comment]
_Also, I have to admit that I'm extremely bad in legal matters, so sorry for a silly question, but I'm just curious._
Is a text file describing project's ABI considered as a subject matter of copyright?

**Comment by LVMVRQUXL** [comment]
> _Also, I have to admit that I'm extremely bad in legal matters, so sorry for a silly question, but I'm just curious._ Is a text file describing project's ABI considered as a subject matter of copyright?

This is a good question @fzhinkin that I recently asked myself. For instance, I've decided to only put the copyright notice in the license of the [Kotools Types](https://github.com/kotools/types) library instead of polluting all files, including the ABI.
So I can say that this suggestion is no more a need for my projects.

**Comment by fzhinkin** [comment]
Closing the issue for now, feel free to reopen it.
