### ISSUE TITLE
Provide a plugin ID that complies with modern Gradle conventions

### ISSUE THREAD

**Issue by JakeWharton** [Kotlin/binary-compatibility-validator#169]
Per https://docs.gradle.org/current/userguide/custom_plugins.html#sec:creating_a_plugin_id

> Plugin ids are fully qualified in a manner similar to Java packages (i.e. a reverse domain name). This helps to avoid collisions and provides a way to group plugins with similar ownership.

Please provide a plugin ID in this form. The old one can remain as an alias or undergo a deprecation cycle.

I would assume given the Maven coordinates that it should be `org.jetbrains.kotlinx.binary-compatibility-validator`.

**Comment by martinbonnin** [comment]
I think this can be closed with https://github.com/Kotlin/binary-compatibility-validator/commit/31f9d02c76e8274429bbdf43f5d99a1c854d99c1 ?
