### ISSUE TITLE
Make KLib validation related tasks public

### ISSUE THREAD

**Issue by fzhinkin** [Kotlin/binary-compatibility-validator#203]
Currently, all tasks required for klib validation are internal.

We should make these tasks public (and cleanup the API along the way), so those who can't directly apply our plugin could incorporate them into custom plugins without writing identical tasks using programmatic API.

**Comment by aSemy** [comment]
Would you consider splitting them out into a separate subproject? It would help with making the Gradle Plugin more idiomatic, being able to test them in isolation, and keeping user's build script classpaths cleaner.

Currently BCV leaks all its dependencies required for KLib validation into the build script classpath, but the KLib validation is only required during task execution, not during build configuration.
