### ISSUE TITLE
Build fails if api is not dumped

### ISSUE THREAD

**Issue by altavir** [Kotlin/binary-compatibility-validator#21]
The build fails with non-informative error (directory not found) if the initial API dump is not done before the build.
I think that the default behavior should be to give a warning and ignore the plugin altogether.

**Comment by qwwdfsad** [comment]
Skipping the validation as the default behaviour for an applied plugin is a no-go. If skipping is the desired behaviour, the plugin shouldn't have been applied in the first place.

Added clear exception message instead
