### ISSUE TITLE
@JvmOverloads doesn't generate different methods for compose functions

### ISSUE THREAD

**Issue by diklimchuk** [Kotlin/binary-compatibility-validator#213]
If i create a composable with @JvmOverloads annotation: 
```
@JvmOverloads
@Composable
public fun Test(
    x: Int,
    y: String = "",
): Unit = Unit
```
the task `apiDump` generaties a single method instead of two different overloads of the same method:
```
public final class com/vk/id/onetap/compose/onetap/TmpKt {
	public static final fun Test (ILjava/lang/String;Landroidx/compose/runtime/Composer;II)V
}
```

If the same is run without @Composable annotation the task correctly dumps two methods into the api file

**Comment by fzhinkin** [comment]
@diklimchuk, it seems like once the Compose compiler plugin transformed `@Composable` functions, there are no default args anymore, so `@JvmOverloads` has no effect. You can check compiled classfiles to ensure that overloads were not included in the dump because they don't exist.

**Comment by diklimchuk** [comment]
Thank you, this resolves my problem
