### ISSUE TITLE
Unknown native target errors with Kotlin 2.0.0-RC1

### ISSUE THREAD

**Issue by rickclephas** [Kotlin/binary-compatibility-validator#218]
Running `apiDump` and `apiCheck` results in errors for all the native targets:
```
Unknown native target: Native(name=linux_arm64)
```

Based on the error message and the change logs for 2.0.0-RC1, it looks like this error is caused by:
https://github.com/JetBrains/kotlin/commit/4941094521f1c49acd13192bde64108fcee44fd2 as part of [KT-66367](https://youtrack.jetbrains.com/issue/KT-66367).

**Comment by rickclephas** [comment]
FYI reported in the Kotlin Slack as well as I am not sure if this change is expected:
https://kotlinlang.slack.com/archives/C0KLZSCHF/p1713085451319519

**Comment by rickclephas** [comment]
In case you need a reproducer: run `./gradlew apiDump` on https://github.com/rickclephas/KMP-NativeCoroutines/commit/db43921687ec5dced78adce4223ee68b0a3eb08e

**Comment by atyrin** [comment]
@rickclephas thank you for the report. We will address in on the Kotlin side: https://youtrack.jetbrains.com/issue/KT-67401/KLib-ABI-dump-write-plain-targets-in-the-manifest

**Comment by rickclephas** [comment]
I can confirm this has been fixed by [KT-67401](https://youtrack.jetbrains.com/issue/KT-67401) in Kotlin 2.0.0-RC2
