### ISSUE TITLE
Do not report protected functions in sealed classes as public API

### ISSUE THREAD

**Issue by drewhamilton** [Kotlin/binary-compatibility-validator#22]
Sealed classes cannot be externally extended, so protected functions are effectively internal.

**Comment by cy6erGn0m** [comment]
It's not exactly true since a sealed class may have an open/abstract sub-class so protected members become public API as well

**Comment by drewhamilton** [comment]
Huh, it did not occur to me that sealed classes could have open subclasses. Would there be a way for this tool to check whether any of a given sealed class's subclasses are open, and then report the protected members accordingly?

**Comment by qwwdfsad** [comment]
Apart from complications with sealed hierarchy analysis (separate and incremental compilation and so on), please note that `protected` function can be invoked from Java from the same package.

So `protected` function is part of public ABI and should be reported
