### ISSUE TITLE
Add Gradle version compatibility tests

### ISSUE THREAD

**Issue by fzhinkin** [Kotlin/binary-compatibility-validator#222]
Readme claims that BCV works with Gradle >= `6.0`.

There are no tests checking that, so we need to add them.

**Comment by aSemy** [comment]
> for some reason, tests use project's Kotlin version (1.9.22) instead of the version specified in the test's build config

This is probably because of `withPluginClasspath()`

https://github.com/Kotlin/binary-compatibility-validator/blob/3a7003363502236e64bbf044540e569b3eb808a4/src/functionalTest/kotlin/kotlinx/validation/api/TestDsl.kt#L40

**Comment by shanshin** [comment]
Added simple tests for minimal and major versions in https://github.com/Kotlin/binary-compatibility-validator/blob/18cd0df801cde896675b0a4b6fdf082e3eef33f7/src/functionalTest/kotlin/kotlinx/validation/test/GradleCompatibilityTest.kt#L15
