### ISSUE TITLE
Description of a Syncs API task is uninformative

### ISSUE THREAD

**Issue by illarionov** [Kotlin/binary-compatibility-validator#228]
When running `./gradlew tasks` in a project with the plugin applied, the Syncs API task description can look a bit cryptic:

```log
Other tasks
-----------
androidApiDump - Syncs API from build dir to map(map(provider(?))) dir for sqlite-open-helper
apiDump - Task that collects all target specific dump tasks
jvmApiDump - Syncs API from build dir to map(map(provider(?))) dir for common-api
```

In this description, the `map(map(provider(?)))` part does not provide any meaningful information and is somewhat redundant. Given that *task.description* is not a lazy property in Gradle, I think the destination directory could be removed from this description.

**Comment by fzhinkin** [comment]
@illarionov, thanks for reporting the issue!
