### ISSUE TITLE
Remove case-insensitive dump file names handling logic

### ISSUE THREAD

**Issue by fzhinkin** [Kotlin/binary-compatibility-validator#231]
https://github.com/Kotlin/binary-compatibility-validator/pull/79 and https://github.com/Kotlin/binary-compatibility-validator/pull/84 addressed the issue reported in https://github.com/Kotlin/binary-compatibility-validator/issues/76 by looking up `.api` files in a case-insensitive manner.

To make things work smoothly on the Gradle side, we need to:
- keep track of individual files instead of a directory containing these files (which is not possible with how we supported case-insensitivity)
- keep track of directories (for check tasks, it's how we did it previously).

The latter option should work, but it requires specifying input/output directories and a file name for all the tasks. Otherwise, Gradle won't be able to track dependencies between tasks correctly. Also, all tasks consuming `.api` files from the repo should be updated to support case-insensitive file names (and for Klibs, the majority of tasks need it).

Note that before all the klib-related changes, the check task was using directories as its inputs, while the dump task was using files as its output, so the only way to enforce dependency between these tasks was `dependsOn` call.

Looking at #76 I'm not sure if macOS's case insensitivity was the root cause. The `:apiDump` task was based on `Sync`, which wipes out the destination directory before copying files. Even if the dump had a name with the wrong characters case, rerunning `apiDump` should have fixed it.

So, I propose removing all the logic for case-insensitive file names from the BCV and using exact file paths as Gradle task inputs/outputs.

**Comment by fzhinkin** [comment]
@ZacSweers do you have a project that relies on it?

**Comment by ZacSweers** [comment]
I don't have any projects that desire case sensitivity. The last issue was that it unexpectedly failed on CI due to CI running linux

**Comment by fzhinkin** [comment]
Looking at #76 once again. The problem is how git works on case-insensitive file systems:
- if `core.ignorecase` (introduced in git `v1.5.6`) is `true` (that would be the default), generated `projectname.api` file will be considered as just an update of `ProjectName.api`, on systems with case-sensitive FS, that would result in a missing dump file;
- with `core.ignorecase=false`, if a dump file not only changed the name, but its content was also updated, git will see a new file, but it will also update the old file, resulting in a two files in the index (and you can't check them out simultaneously on case-insensitive FS), so a `git mv` call would be needed.

**Comment by joffrey-bion** [comment]
Wouldn't it "just work(TM)" to make the BCV delete the old file in a caae-insensitive manner, and recreate it with an exact match of the project name every time?

**Comment by fzhinkin** [comment]
BCV was always deleting the old file, the problem is how git track deletion and creation of a new file:
- with default git repo settings:
```
$ git init

$ echo "yo" > AAA.txt; git add AAA.txt; git commit -a -m 'added AAA.txt'
$ rm AAA.txt; echo YO > aaa.txt
$ git add .
$ git status
On branch main
Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
	modified:   AAA.txt

$ ls
aaa.txt
```

- with `core.ignorecase=false`
```
$ git init
$ echo "yo" > AAA.txt; git add AAA.txt; git commit -a -m 'added AAA.txt'
# please take care of case-insentiveness
$ git config core.ignorecase false
$ rm AAA.txt; echo YO > aaa.txt
$ git add .
$ git status
On branch main
Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
	modified:   AAA.txt
	new file:   aaa.txt

$ echo '🤡'
```

The only proper way to handle file name case change is `git mv`:
```
$ git mv AAA.txt aaa.txt
$ git status
On branch main
Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
	deleted:    AAA.txt
	new file:   aaa.txt
```

**Comment by joffrey-bion** [comment]
Yes, understood. Sorry I was too slow to update my comment apparently.

I can't believe git works this way by default. This is quite enraging. Now, is it the responsibility of BCV to deal with it? Maybe, maybe not. If we can make the experience better, why not.

So, based on what you said, even being strict from the BCV side during `apiDump` doesn't guarantee anything, because people could change the case of their project name between 2 generations, and git will happily save the wrong case.

I guess that leaves us no choice but to be case insensitive on the `apiCheck` side.

**Comment by fzhinkin** [comment]
In general, it's nice to provide a better user experience.

However, those who use `core.ignorecase false` continue having problems (althougt it should be easier to spot the problem).
Also, as Gradle tasks have to use directories as their inputs instead of precise file locations, and also because we store both JVM and Klibs dump in the same folder, every update of one of these dumps will invalidate all dependent tasks, which is not very nice.

**Comment by joffrey-bion** [comment]
> However, those who use `core.ignorecase false` continue having problems (althougt it should be easier to spot the problem).

Could you please expand on that? If people use `core.ignorecase=false`, the `apiDump` task will always generate correct files, and git will commit them in the correct case, right?

**Comment by fzhinkin** [comment]
> For the record, this is actually not quite correct. Git's default depends on the case-sensitivity of the local OS. So in case-sensitive systems, `core.ignorecase` will be false by default, which is best.

Well, yeah, that's true. I meant how it works on macOs & Windows.

> Could you please expand on that? If people use `core.ignorecase=false`, the `apiDump` task will always generate correct files, and git will commit them in the correct case, right?

Not quite. Without `git mv,` git can't detect old file removal but sees only new file creation. So, a user may end up with the two files in repo:
```
$ git init;
$ git config core.ignorecase false
$ echo 123 > zzz
$ git add zzz; git commit -a -m 'initial'
$ mv zzz ZZZ
$ git add ZZZ; git commit -a -m 'rename'
$ git ls-files
ZZZ
zzz
```

**Comment by joffrey-bion** [comment]
> Not quite. Without git mv, git can't detect old file removal but sees only new file creation. So, a user may end up with the two files in repo

I don't quite get that point. I mean, this would happen in all systems, and with all renames, regardless of whether it's just a case change or not. It's just user error with git commands (just doing `git add ZZZ` isn't sufficient to register the whole rename, you would need a `git rm -f zzz`, or to use `git mv` in the first place, or just commit this from your IDE which should deal with it properly).

Also, if the user renames their project (which is the case that leads to this kind of stuff), won't they have to deal with this manually for the directory itself and other files named after the project anyway?

**Comment by fzhinkin** [comment]
> I don't quite get that point. I mean, this would happen in all systems, and with all renames, regardless of whether it's just a case change or not. It's just user error with git commands (just doing `git add ZZZ` isn't sufficient to register the whole rename, you would need a `git add zzz` too, or to use `git mv` in the first place, or just commit this from your IDE which should deal with it properly).

Assuming that a user uses an IDE to work with a project, if a file rename is performed using GUI, everything will go through underlying VCS's commands, and the rename will be handled correctly.

But it's not the case for BCV, where a file is renamed during Gradle's command execution.

As a user who renamed a project and rerun `apiDump`, I'll see the following in IDEA's CSV commit view:
- if `ignorecase` is `true`, there will be no changes in `.api` files;
- if `ignorecase` is `false`, there will be no changes in an old file, and there will be a new untracked `.api` file. So nothing would hint me to remove an old file from index.

> Also, if the user renames their project (which is the case that leads to this kind of stuff), won't they have to deal with this manually for the directory itself and other files named after the project anyway?

That poses a question: why should BCV handle scenarios when someone forgets to perform some related actions after renaming a project?

**Comment by fzhinkin** [comment]
I'm leaning toward API dump filename case mismatch no longer being tolerable on case-sensitive filesystems.

The decision could always be reconsidered, but if the issue becomes annoying, I'd rather detach dump file names from project names (#233).
