### ISSUE TITLE
Migrate to newer kotlin-metadata-jvm

### ISSUE THREAD

**Issue by sandwwraith** [Kotlin/binary-compatibility-validator#241]
Currently (https://github.com/Kotlin/binary-compatibility-validator/blob/29a83d78596bfdbc37f885da881edc40021eb073/gradle/libs.versions.toml#L18) BCV uses kotlinx-metadata-jvm 0.6.2. This version uses some obsolete APIs, and it is recommended to migrate to the latest stable version with a different package. Moreover, it is required to be able to read Kotlin 2.1 language version (to which master branch of Kotlin will be switched soon).

Changleg and migration guide are available here:
https://github.com/JetBrains/kotlin/blob/75c87dd8585147b4abab2ac262fac84a037f07be/libraries/kotlinx-metadata/jvm/Migration.md#L1
https://github.com/JetBrains/kotlin/blob/75c87dd8585147b4abab2ac262fac84a037f07be/libraries/kotlinx-metadata/jvm/ChangeLog.md

**Comment by fzhinkin** [comment]
It's relatively easy to update the code (see [update-metadata-lib](https://github.com/Kotlin/binary-compatibility-validator/tree/update-metadata-lib) branch), but `kotlin-metadata-jvm:2.0.0` will bring transitive dependency on `stdlib:2.0.0`, so https://github.com/Kotlin/binary-compatibility-validator/issues/208 needs to be done first.

**Comment by lukellmann** [comment]
`org.jetbrains.kotlinx:kotlinx-metadata-jvm:0.6.2` will also no longer work with Kotlin 2.1.0, see https://github.com/kordlib/kord/commit/9a90ee0f5b669a017a0b04caf53eaee8fd02f9fe

**Comment by sandwwraith** [comment]
@fzhinkin Is there a problem with releasing just `update-metadata-lib`? Kotlin master is already switched to 2.1

**Comment by fzhinkin** [comment]
@sandwwraith, the issue with `update-metadata-lib` is that `kotlin-metadata-jvm` will bring the stdlib `2.0` as a dependency.

**Comment by fzhinkin** [comment]
Ok, I'm wrong.

**Comment by sandwwraith** [comment]
But isn't BCV itself using stdlib 2.0 already? 🤔

**Comment by fzhinkin** [comment]
No, it's not.

**Comment by fzhinkin** [comment]
Yeah, I was wrong. Opened the PR: #255.
Once it is merged, a new version with Kotlin 2.1 support will be released.
