### ISSUE TITLE
JVM/Android-only modules create empty klib.api file on 0.15.0-Beta.3

### ISSUE THREAD

**Issue by colinrtwhite** [Kotlin/binary-compatibility-validator#246]
On `0.15.0-Beta.3`, the plugin generates an empty `klib.api` if the [module only supports Android/JVM targets](https://github.com/coil-kt/coil/blob/main/coil-network-okhttp/build.gradle.kts#L16). This causes the binary compatibility check to fail with the error `Project ABI file XYZ.klib.api is empty.`. The release notes mention adding modules to `ignoredProjects`, but I believe that also disables checking the `android/XYZ.api` and `jvm/XYZ.api` files. I have the new klib validation support enabled with `strictValidation = true`:

```kotlin
klib {
    enabled = true
    strictValidation = true
}
```

To reproduce:

Run `./gradlew apiDump` and then `./gradlew apiCheck` in [this project](https://github.com/coil-kt/coil/pull/2343). I can make a smaller repro project if needed.

**Comment by fzhinkin** [comment]
@colinrtwhite thanks for reporting!
