### ISSUE TITLE
introduce ignoredClasses in gradle plugin

### ISSUE THREAD

**Issue by SergejIsbrecht** [Kotlin/binary-compatibility-validator#25]
Type: Feat. request

Issue:
Android-Projects create a `BuildConfig` for android-libraries, which is public. It is not possible to exclude the package, because other needed classes are in given package. Also it is not possible to use an annotation, because it is generated.

Suggestion:
Introduce new `ignoredClasses` flag in gradle

Code
```
ignoredClasses += ["com.my.package.MyClazz"]
```

Note:
When this feat. is approved, I would implement it quickly and create a PR.

**Comment by qwwdfsad** [comment]
Thanks for raising the issue! Yes, this addition seems reasonable

**Comment by SergejIsbrecht** [comment]
I am on it. The addition only contains some lines of code, but I will add some gradle-tests for better coverage, that no regression is added at some point.
