### ISSUE TITLE
Tags and changelog missing for 0.16.1 and 0.16.2

### ISSUE THREAD

**Issue by TheMrMilchmann** [Kotlin/binary-compatibility-validator#259]
No release has been tagged on GitHub for these versions and there is no trace of these tags in the git repository. As the documentation (README) has already been updated to suggest installing `0.16.2`, I wonder if this was just forgotten. As far as I can tell, this also means that no changelog is available for these versions, which is a pity as it's hard to determine what's in there now.

**Comment by fzhinkin** [comment]
Published release notes for `0.16.2`: https://github.com/Kotlin/binary-compatibility-validator/releases/tag/0.16.2
`0.16.1` was broken and should not be used, but it contains the same changes as `0.16.1`.
