### ISSUE TITLE
The binary-compatibility-validator API module published on Maven central does not declare dependency on ASM and kotlin-metadata-jvm

### ISSUE THREAD

**Issue by mikaelstaldal** [Kotlin/binary-compatibility-validator#278]
The [binary-compatibility-validator API module published on Maven central](https://central.sonatype.com/artifact/org.jetbrains.kotlinx/binary-compatibility-validator/0.16.3/overview) does not declare dependency on `org.ow2.asm:asm`, `org.ow2.asm:asm-tree`, `org.jetbrains.kotlin:kotlin-metadata-jvm`.

**Comment by fzhinkin** [comment]
> So how come I found this? https://central.sonatype.com/artifact/org.jetbrains.kotlinx/binary-compatibility-validator/0.16.3/overview

As I wrote:

> `org.jetbrains.kotlinx:binary-compatibility-validator` is the Gradle plugin's implementation

That does not contradict the fact that it comes bundled with an API. However, it is not a standalone library, thus its dependencies are managed they way they are managed.

**Comment by mikaelstaldal** [comment]
> > So how come I found this? https://central.sonatype.com/artifact/org.jetbrains.kotlinx/binary-compatibility-validator/0.16.3/overview
> 
> As I wrote:
> 
> > `org.jetbrains.kotlinx:binary-compatibility-validator` is the Gradle plugin's implementation
> 
> That does not contradict the fact that it comes bundled with an API. However, it is not a standalone library, thus its dependencies are managed they way they are managed.

How am someone who stumble upon it on Maven Central supposed to know it's not a standalone library?

**Comment by fzhinkin** [comment]
> How am someone who stumble upon it on Maven Central supposed to know it's not a standalone library?

There's a link to this repository, and it is clearly stated that BCV is a Gradle plugin.

But yeah, artifact's description could be improved.

**Comment by fzhinkin** [comment]
And we should also include details on required additional dependencies for those who use the plugin as a library.

**Comment by mikaelstaldal** [comment]
It seems like the `kotlinx.validation.api` package doesn't have any Gradle dependencies, so that package can be considered a library. What about actually releasing that as a proper library (with correct dependencies)? Should be quite easy to do I think.

**Comment by fzhinkin** [comment]
Currently, BCV is migrating to the Kotlin repository (#223, https://youtrack.jetbrains.com/issue/KT-71098); the split into a plugin and a separate library most likely will happen after the migration complete.

**Comment by mikaelstaldal** [comment]
> Currently, BCV is migrating to the Kotlin repository (#223, https://youtrack.jetbrains.com/issue/KT-71098); the split into a plugin and a separate library most likely will happen after the migration complete.

Sounds good. In the mean time, [I](https://gitlab.com/chromaway/core-tools/kotlin-bcv-maven-plugin) and [others](https://github.com/adamko-dev/kotlin-binary-compatibility-validator-mu/) will use the current Gradle plugin module as a library
