### ISSUE TITLE
Plugin marker is missing on Gradle Portal

### ISSUE THREAD

**Issue by cortinico** [Kotlin/binary-compatibility-validator#46]
A follow up from #44 

I suppose the plugin is now published on Gradle Portal 🎉  

However, it looks like the publishing is missing the Gradle marker. The only way to use this plugin with the `plugins{}` block that you mention in the README is by providing a rule in the `resolutionStrategy` on the `settings.gradle.kts` file:

```
pluginManagement {
    resolutionStrategy {
        eachPlugin {
            if (requested.id.id == "binary-compatibility-validator") {
                useModule("org.jetbrains.kotlinx:binary-compatibility-validator:${requested.version}")
            }
        }
    }
}
```

You can find a real world example here: https://github.com/cortinico/ktfmt-gradle/blob/b6f8a55bfd8334dccacb7f28335176534cb8ee27/plugin-build/settings.gradle.kts#L2-L8

I'm not entirely sure what is happening as it seems like the plugin is actually on the Gradle portal here: https://plugins.gradle.org/m2/org/jetbrains/kotlinx/binary-compatibility-validator/0.4.0/

While the WebUI will show just a blank page, the artifacts will still resolve correctly.

Can I ask you to clarify how you published the plugin on Gradle Portal? Also having a badge on the readme would be useful :)

**Comment by Him188** [comment]
Maybe this is because `pluginBundle` is missing in the buildacript?

Example here: https://github.com/mamoe/mirai-console/blob/8d568543f2c19bc19ebb2eeaa3c1767e4c4acce3/tools/gradle-plugin/build.gradle.kts#L48-L52

**Comment by ilya-g** [comment]
We haven't published the plugin marker to Gradle plugin portal, but we have published it to Maven Central instead.
Gradle plugin portal proxies Maven Central, so it can resolve the plugin, even if the plugin doesn't have its dedicated page on the portal.

No special resolution strategy should be needed.

**Comment by cortinico** [comment]
Thanks for the update 👍 It worked like a charm
