### ISSUE TITLE
Handle TypeErasure

### ISSUE THREAD

**Issue by hfhbd** [Kotlin/binary-compatibility-validator#52]
````kotlin
public suspend fun foo(): String
// change to 
public suspend fun foo(): Int
````
The api is always `public final fun foo (Lkotlin/coroutines/Continuation;)Ljava/lang/Object;` and the `apiCheck` will not fail.

**Comment by qwwdfsad** [comment]
Thanks for the report! It's hard to tell whether or not this is in the scope of **binary** compatibility validator, but it is definitely worth considering for us and the purpose of the tool as the whole

**Comment by hfhbd** [comment]
Same happens with a lambda/function argument:
```kotlin
fun foo(action: () -> Unit)
// change to 
fun foo(action: () -> Int)
```
api is always: 
`public final fun foo (Lkotlin/jvm/functions/Function1;)V`

**Comment by qwwdfsad** [comment]
Could you please elaborate on "is mostly not expected" part?
Do you mean it is not expected that binary compatibility tool doesn't track it or something else?

**Comment by hfhbd** [comment]
@qwwdfsad Yes. Thinking in Kotlin JVM, the binary did not change, so this behavior is expected. But thinking in Kotlin common code, this behavior is not expected. 

For example, I did change the function in common code, I expected at first a failing `apiCheck`, but the check did not fail, and I forgot the jvm type erasure. When publishing this change in a new version, the Kotlin api is changed, and Kotlin consumer, which are the main consumer of a Kotlin library, needs to fix their code. 

 I like the tool for binary jvm compatibility, but I would love to see direct Kotlin API/binary compatibility support.

**Comment by qwwdfsad** [comment]
Thanks for the explanation!

Regarding common code -- unfortunately, our ABI compatibility rules are not yet established, so we cannot establish them in BCV as well.
Regarding JVM ABI and type erasure -- noted, we'll take it into account when decided the fate of BCV regarding generics, nullability and other on-the-edge of ABI cases. Thanks!

**Comment by qwwdfsad** [comment]
Closing as won't fix, for now, keeping the tool as simple as possible
