### ISSUE TITLE
Non-public markers aren't handled correctly for functions with default parameters

### ISSUE THREAD

**Issue by zsmb13** [Kotlin/binary-compatibility-validator#58]
When declaring an opt-in annotation and adding that annotation to the `nonPublicMarkers` configuration, functions that have default parameters are not correctly excluded from the api dump - the generated `$default` function is still included. A very similar issue to the one fixed in https://github.com/Kotlin/binary-compatibility-validator/pull/30.

Example annotation:

```kotlin
@RequiresOptIn(level = RequiresOptIn.Level.WARNING)
annotation class MyInternalApi
```

An example function:

```kotiln
@MyInternalApi
fun defParamInternalFun(x: Int = 0) {}
```

The incorrect API dump:

```
public final class co/zsmb/example/MainKt {
	public static synthetic fun defParamInternalFun$default (IILjava/lang/Object;)V
}
```

Project with examples and reproducing the issue can be found [here](https://github.com/zsmb13/binary-compat-internal-annotation-default-param-issue/).

**Comment by qwwdfsad** [comment]
Fixed in 0.10.0
