### ISSUE TITLE
Support API comparison with published artifact 

### ISSUE THREAD

**Issue by ekursakov** [Kotlin/binary-compatibility-validator#6]
Hi! Thanks for publishing this as separate plugin!

In our team, we use binary-compatibility-validator from Kotlin repository for internal shared libraries but suggested workflow (committing `.api` files to repository) is too strict for us, so instead we implemented comparison with the latest published maven artifact `${project.group}:${project.name}:latest.release`.

At this time we just post an API diff to PRs, but we also have a plans to check only for a binary-incompatible changes by comparing `ClassBinarySignature`/`MemberBinarySignature` contents.

It would be great if similar functionality available in this plugin.

**Comment by qwwdfsad** [comment]
Thanks for the feedback, it's good to know.
Could you please elaborate on how do you configure the fact that `.api` should be retrieved from maven artifact? Do you specify its version and maven repository separately?

>At this time we just post an API diff to PRs

Does it mean that each diffs from all merged PRs after the latest release are included to each new PR?

**Comment by ekursakov** [comment]
> Could you please elaborate on how do you configure the fact that .api should be retrieved from maven artifact? Do you specify its version and maven repository separately?

I created custom `Configuration` named `previousAbi` and call `getBinaryAPI` with jar resolved from it.
 
> Does it mean that each diffs from all merged PRs after the latest release are included to each new PR?

CI for these libs is configured to publish new patch version on every merge to `dev` branch, so we didn't encounter problems with overlapping diffs so far, but now I see possible problems with this approach.

**Comment by qwwdfsad** [comment]
This can be achieved manually by depending on `binary-compatibility-validator` as plain JAR and using its API to retrieve the dump
