### ISSUE TITLE
Is `runtime` vs `compile` time scope in a POM considered?

### ISSUE THREAD

**Issue by ZakTaccardi** [Kotlin/binary-compatibility-validator#7]
Our use case is that we have a multi-module project that we ship as an SDK - so many modules in it are effectively public - but our "clients" consume from only a specific module point - so many of those `public` classes in upstream projects are not on the `compile` (in the `.pom`) scope, but in the `runtime` scope.

We make breaking changes to our `runtime` API frequently, but can we use this tool to limit changes to our `compile` API as our SDK is consumed from the point of view of a specific module?

Example:

`:a` - consumed by client
`:b` - consumed by `:a` as an `implementation` dependency
`:c` - consumed by `:a` as an `implementation` dependency
`:d` - consumed by `:a` as an `api` dependency

We want to be notified of breaking public API changes to `:a` and `:d`, but not `:b` and `:c`

**Comment by qwwdfsad** [comment]
No specific dependency kinds are considered as it may be too application-specific and, typically, unknown at the moment of the build.

>We want to be notified of breaking public API changes to :a and :d, but not :b and :c

You can exclude `b` and `c` in the corresponding extension:
```
// build.gradle
apiValidation {
    ignoredProjects += ["b", "c"]
}
```

**Comment by qwwdfsad** [comment]
Also, please note that projects built with `kotlin-android` plugin are not supported in the latest version.
Its support is in `master` though (#4), I just struggle to find the time to properly cover it with integration tests.
