### ISSUE TITLE
Is it possible to distinguish between compatible and incompatible changes? 

### ISSUE THREAD

**Issue by martinbonnin** [Kotlin/binary-compatibility-validator#70]
When monitoring public API, I can think of two use cases:

1. Make sure that `module.api` files are always up-to-date and represent the latest state of the public API.
2. Make sure that a new version of `module.api` is backward compatible with the previous one to avoid breaking changes.

In the case of 1., it's important to detect additions as we want them to be taken into account in subsequents checks. 

But additions are typically not important for 2.: It is fine to release a new version of a lib with new APIs as it will not break backward compatibility.

My current understanding is that `./gradlew apiCheck` is focused at 1. and will fail on any change, even additions. Am I correct? 

If that's the case, it would be nice to have another task focused at 2. that will only succeed if the new API is backward compatible. 

Maybe `./gradlew apiDumpSafe` ?

It would fail on backward incompatible changes only and output a report with the problematic changes and whether they are source-level or binary-level incompatibilities. 

Is that currently possible? Or will it be?

**Comment by qwwdfsad** [comment]
Sorry for the extremely late reply.

Alas, I only see that such a mode may make the API changes less robust and easier to break.

When the authors use `apiDumpSafe` and `check` checks only safe API, nothing prevents API authors to release new API without updating `module.api` file to reflect the fact that any changes in these signatures are now considered breaking.

Additionally, such mode is not intended as the main usage pattern of this tool and having it operating in two modes means twice as much testing and maintenance. 

I can suggest an alternative -- it is possible to depend on `binary-compatibility-validator` as a JAR with public API (that mostly dumps `.api` files) and post-process the results in the way you need it

**Comment by martinbonnin** [comment]
> When the authors use apiDumpSafe and check checks only safe API, nothing prevents API authors to release new API without updating module.api file to reflect the fact that any changes in these signatures are now considered breaking.

Not sure I follow... There would be 2 use cases:

1. library is stable. Maintainers call `apiDumpSafe`. Only additions are allowed.
2. library is not stable. Maintainers call `apiDump` to overwrite whatever API was there before. Breaking changes are allowed.

In all cases, the CI calls `apiCheck` and returns an error if the committed files does not match the API. 

Japicmp for an example has something like this where it shows what is breaking and what is non-breaking.

> and post-process the results in the way you need it

Sure. I'd argue my needs aren't that specific. So if that post processing could be in a central first-party place, that'd benefit the ecosystem as a whole but I can try to work on something at some point :)

**Comment by qwwdfsad** [comment]
>library is stable. Maintainers call apiDumpSafe. Only additions are allowed.

Alas, it's more complex than that. Moving methods in hierarchy chains is fully compatible, removing overrides is compatible (as long as it's not a covariant override), removing `final` modifier is binary compatible. Removing `inline` function is compatible as long as you expected it to be used only from Kotlin (e.g. it hasn't implied Kotlin interop or had mangled name/value classes etc.).

Addressing all that is a really complex task. So we either have to support all of it or provide a half-baked alternative that is a subset of what is actually allowed. I would like to avoid doing both :)

>Japicmp for an example has something like this where it shows what is breaking and what is non-breaking.

That's cool! Could you please share a pointer to the specific japicmp mode/API?

**Comment by martinbonnin** [comment]
> Addressing all that is a really complex task. So we either have to support all of it or provide a half-baked alternative that is a subset of what is actually allowed. I would like to avoid doing both

I see... Damn, that's hard.

> That's cool! Could you please share a pointer to the specific japicmp mode/API?

I usually use japicmp from the command line. For an example, to compare 2 versions of `apollo-runtime`:

```
java -jar japicmp-0.15.6-jar-with-dependencies.jar -o apollo-runtime-2.0.0.jar -n apollo-runtime-2.5.9.jar 
--ignore-missing-classes --error-on-binary-incompatibility -m --html-file japicmp.html
```

This outputs a report like [this](https://storage.googleapis.com/uploadbin.appspot.com/apollo_japicmp.html) with breaking changes in orange/red. Maybe it's not 100% correct but it's still useful information to check compatibility between two versions. It can even distinguish between source vs binary incompatible changes.
