### ISSUE TITLE
Add support of semantic minor change

### ISSUE THREAD

**Issue by misha-dorokhin-fourthline** [Kotlin/binary-compatibility-validator#92]
I am building SDKs and follow [semantic versioning](https://semver.org/). It would be nice to have an option to detect the minor API update during `apiCheck` command. At this moment the added class would fail the `apiCheck` command.

But from SDK consumer point of view this change is compatible with the previous version because it does not require any effort in order to update to it.

Feature request:
- add an option to mark `minor` change as a non-breaking change. `apiCheck` should succeed
- print the added API to the console in this case

**Comment by qwwdfsad** [comment]
Hi, 

It seems like what you are proposing is a higher level of abstraction than `binary-compatibility-validator` operates on. You can build such behaviour on top of BCV programmatic API, but BCV itself neither has notion of semantic versioning nor it should have:

* `apiCheck` is not aware of any versions at all and neither has ways to detect the version for which it checks API for
* It's not clear who is responsible for updating apiDump in that case. What prevents you from adding a new API in minor version `1` and removing it in minor version `2` if the dump is not updated?
*  Different libraries have different notions of compatibility. For example, Kotlin itself is not allowed to add any new non-experimental API in minor releases, while using this tool and we would like to keep it that way
