### ISSUE TITLE
Is an added 'synthetic' considered to be a compatible change?

### ISSUE THREAD

**Issue by obet912** [Kotlin/binary-compatibility-validator#93]
(This is not a bug, just a question)
To one of my functions, a `synthetic` was added in the .api file.

Before:
`public final fun myFunction (Ljava/util/List;)I`
After:
`public final synthetic fun myFunction (Ljava/util/List;)I`

Would this be considered to be a non-breaking change?

**Comment by qwwdfsad** [comment]
In terms of ABI -- yes, it is. 
In terms of source compatibility -- it is not.
